export const ROLES = ['SUPER_ADMIN', 'ADMIN', 'MEMBER'];
export const MEMBERSHIP_STATUSES = ['NO_MEMBERSHIP', 'ACTIVE', 'UPCOMING', 'EXPIRED', 'CANCELLED'];
export const PAYMENT_STATUSES = ['PENDING', 'COMPLETED', 'FAILED', 'REFUNDED'];
export const PAYMENT_GATEWAYS = ['CASH', 'RAZORPAY', 'PHONEPE'];
export const COUPON_TYPES = ['PERCENTAGE', 'FLAT'];
